# -*- coding: utf-8 -*-

from odoo import models, fields, api


class kegiatan(models.Model):
    _name = 'isa_data.kegiatan'
    _description = 'isa_data.kegiatan'

    tanggal = fields.Date(string='Tanggal', required=True)
    name = fields.Text(string='Kegiatan', required=True)
    jemaat = fields.Many2one('isa_data.jemaat', string='Jemaat', required=True)
    kelompok = fields.Many2one('isa_data.jemaat_kelompok', string='Kelompok Jemaat')
    kegiatan_jenis = fields.Many2one('isa_data.kegiatan_jenis', string='Jenis Kegiatan', required=True)
    tablig_nama = fields.Text(string='Nama yang Ditabligi')
    tablig_jumlah = fields.Integer(string='Jumlah yang Ditabligi')
    tablig_poin = fields.Text(string='Poin Materi Tablig')
    tablig_tanggapan = fields.Text(string='Tanggapan dari yang Ditabligi')
    tablig_literatur = fields.Integer(string='Berapa Literatur yang Dibagikan')
    tablig_mb = fields.Integer(string='Berapa Mubayyi\'in')
    tablig_mb_online = fields.Selection([
    	('0', 'Belum'),
    	('1', 'Sudah')
    	], 'Sudah Masuk MB Online', default='0')
    tablig_ans = fields.Integer(string='Berapa Anshar yang Bertablig')
    tablig_khd = fields.Integer(string='Berapa Khuddam yang Bertablig')
    tablig_li = fields.Integer(string='Berapa LI yang Bertablig')
    tablig_atf = fields.Integer(string='Berapa Athfal yang Bertablig')
    tablig_nai = fields.Integer(string='Berapa Nashirat yang Bertablig')
    tablig_kisah_baiat = fields.Text(string='Kisah Baiat')
    rabtah_nama = fields.Text(string='Nama yang Dirabtahi')
    rabtah_jumlah = fields.Integer(string='Jumlah yang Dirabtahi')
    rabtah_poin = fields.Text(string='Poin dan Cara Rabtah')
    rabtah_tanggapan = fields.Text(string='Tanggapan dari yang Dirabtahi')
    rabtah_ans = fields.Integer(string='Berapa Anshar yang Melakukan Rabtah')
    rabtah_khd = fields.Integer(string='Berapa Khuddam yang Melakukan Rabtah')
    rabtah_li = fields.Integer(string='Berapa LI yang Melakukan Rabtah')
    rabtah_atf = fields.Integer(string='Berapa Athfal yang Melakukan Rabtah')
    rabtah_nai = fields.Integer(string='Berapa Nashirat yang Melakukan Rabtah')
    tarbiyat_poin = fields.Text(string='Poin Tarbiyat')
    tarbiyat_ans = fields.Integer(string='Berapa Anshar yang Mengikuti Tarbiyat')
    tarbiyat_khd = fields.Integer(string='Berapa Khuddam yang Mengikuti Tarbiyat')
    tarbiyat_li = fields.Integer(string='Berapa LI yang Mengikuti Tarbiyat')
    tarbiyat_atf = fields.Integer(string='Berapa Athfal yang Mengikuti Tarbiyat')
    tarbiyat_nai = fields.Integer(string='Berapa Nashirat yang Mengikuti Tarbiyat')
    kunjungan_jemaat = fields.Many2one('isa_data.jemaat', string='Jemaat Lain yang Dikunjungi')
    kunjungan_nama = fields.Text(string='Nama-nama yang Dikunjungi')
    kunjungan_jumlah = fields.Integer(string='Jumlah yang Dikunjungi')
    kunjungan_poin = fields.Text(string='Poin Tarbiyat dalam Kunjungan')
    talimulquran_poin = fields.Text(string='Materi Ta\'limul Quran')
    talimulquran_ans = fields.Integer(string='Berapa Anshar yang Mengikuti Ta\'limul Qur\'an')
    talimulquran_khd = fields.Integer(string='Berapa Khuddam yang Mengikuti Ta\'limul Qur\'an')
    talimulquran_li = fields.Integer(string='Berapa LI yang Mengikuti Ta\'limul Qur\'an')
    talimulquran_atf = fields.Integer(string='Berapa Athfal yang Mengikuti Ta\'limul Qur\'an')
    talimulquran_nai = fields.Integer(string='Berapa Nashirat yang Mengikuti Ta\'limul Qur\'an')
    mutholaah_buku = fields.Char(string='Judul Buku')
    mutholaah_halaman = fields.Integer(string='Jumlah Halaman')
    keuangan_pembayar = fields.Integer(string='Jumlah Pembayar Candah')
    keuangan_nominal = fields.Integer(string='Jumlah Candah dalam Rupiah')
    artikel_judul = fields.Char(string='Judul Artikel')
    ibadah_tidak_jamaah = fields.Integer(string='Berapa Kali Tidak Shalat Berjamaah')
    ibadah_tidak_tahajjud = fields.Integer(string='Berapa Kali Tidak Tahajjud')
    ibadah_alquran_surah = fields.Many2one('isa_data.alquran_surah', string='Surah yang Dibaca')
    ibadah_alquran_ayat = fields.Integer(string='Ayat Berapa')